# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_auto_20170729_1639'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('UserManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
