# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0003_auto_20170729_1645'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
