# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0004_auto_20170730_0108'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='user_creator',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='review',
        ),
        migrations.AddField(
            model_name='trip',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(default='Fun stuff', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='Spain', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='user_joiner',
            field=models.ManyToManyField(related_name='user_joins', to='log_reg.User'),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
